### ISSUE TITLE
 UITabBarController    have a problem

### ISSUE THREAD

**Issue by SherryTeam** [carsonperrotti/CNPGridMenu#10]
Thank you for your work.
<img width="375" alt="qq20150828-1 2x" src="https://cloud.githubusercontent.com/assets/13001849/9546521/e6b39832-4dc5-11e5-9132-9441f4f768dc.png">

the tabBar is show. how to hide it ?

**Comment by carsonperrotti** [comment]
Try presenting it from `self.tabBarController` instead of `self'. Let me know if that works.
