### ISSUE TITLE
using selectionHandler and font color

### ISSUE THREAD

**Issue by shahankit** [carsonperrotti/CNPGridMenu#7]
How do I use the selectionHandler for button press? Also I removed the image parameter from circleButton of CNPGridMenu and instead added a titleLabel but even though I set the font color it does not changes and has transparent fonts which assumes the color of background. Can you please help how do I set my font color for titleLabel of button.
[cell.circleButton.titleLabel setFont:[UIFont systemFontOfSize:30]]; 
[cell.circleButton setTitleColor:[UIColor blackColor] forState:UIControlStateNormal];

**Comment by eytanbiala** [comment]
+1, how do you change the font color correctly?

**Comment by shahankit** [comment]
@eytanbiala you can check the cnpgridmenu.m file and change the color for button by setting it in collectionview cellForRowAtIndexPath method using setTitleColor property.

**Comment by shahankit** [comment]
@eytanbiala The main reason why fonts appeared transparent was vibrancy, try removing the vibrancy view and you can then set font color easily. It can be changed here : https://github.com/carsonperrotti/CNPGridMenu/blob/master/Source/CNPGridMenu.m#L159
