### ISSUE TITLE
White blank screen in iOS 7.1 device 4s but works fine in simulatore

### ISSUE THREAD

**Issue by ahmi** [carsonperrotti/CNPGridMenu#9]
First of all thanks for very useful component.

I am facing this strange issue , everything works fine in simulator but in device (iPhone 4s iOS 7.1) a white blank irresponsive screen appears with warning "<CNPGridMenu: 0x146ee2c0> UIModalPresentationCustom presentation style can only be used with an animator or with unanimated presentations."
Works fine iOS 8+ with iphone 5,6,6 +
Immediate help will be much appreciated.

Thanks

**Comment by carsonperrotti** [comment]
I'll look into it this weekend and see if I can replicate the issue. I'll let you know if I need more info.

**Comment by ahmi** [comment]
Thanks mate. Another thing. Please change case of "Pod" to "pod" on info page. It doesnt installs with capital "p".

**Comment by ahmi** [comment]
Have you seen it ?

**Comment by ahmi** [comment]
I have tested your Example project it has the same issue .

When it displays blank screen (with iOS 7.0, iPhone 4 and iPhone 5) it gives following warning

Warning: <ViewController: 0x14d760c0>-><CNPGridMenu: 0x14d9b000> UIModalPresentationCustom presentation style can only be used with an animator or with unanimated presentations.

Please fix it asap i have already used it in my applications i have to upload new version. Thanks

**Comment by carsonperrotti** [comment]
I am currently working on 0.2 which will be a complete rewrite. I will try to have it finished as quickly as possible. Keep an eye out for that update. I'll make sure the fix for this is included. Thanks for the info.

**Comment by ahmi** [comment]
Hey, did u get time to check it ?

**Comment by carsonperrotti** [comment]
Sorry for the delay on this one. I just reworked my other Cocoapod and this one is up next. Coming very soon.
